### ISSUE TITLE
[Idea] Color and icons on graph node

### ISSUE THREAD

**Issue by neokeld** [tchayen/markdown-links#17]
Hello,
@tchayen  Thanks a lot for this project ! I come from Foam (issue https://github.com/foambubble/foam/issues/2).

I have some main Markdown documents that in the end are the main nodes of the graph. It can be a widely used idea or a definition.
I would like to highlight these nodes in the graph to quickly see how the graph is organised and where are the main nodes.

A feature i like to see is color / icons on graph node :
When my node is a main node, i want to highlight it (maybe clicking on the node and changing the color).

**Comment by tchayen** [comment]
Hi!

Before we start iterating on a potential solution, I want to clarify just in case that Markdown Links is a general purpose extension for visualising links between Markdown files and some too specific features might not work well for it. Of course I am willing to support Foam, but this is not the first priority.

Back to the topic:

I am not 100% sure what you mean by main nodes in the graph. Let's say we have two groups of connected nodes, so two graphs. How do we tell which node in a given subgraph is the main one?

There are several other similar potential improvements that come to my mind like using different colors for different subgraphs or highlighting edges coming out of the active node but I am not sure if this is what you mean and if this would really help.

**Comment by fmagin** [comment]
A very general solution could be to use markdown metadata (like YAML Front Matter) and allow markdown-links to be configured how to use it.
For example, a markdown file looks like this:
```
---
type: blogpost
tags: topic1, topic2
---
# A very interesting blogpost

* notes
```

now some optional markdown-links config could be setup so the value of `blogpost` in the `type` fields, means that the node should be rendered in a certain way. markdown-links then just supports some basic style options (e.g. color, size, shape of a node?) and some simple ruleset to decide it. E.g. the ruleset could look like

 ```
metadata.type == "blogpost": { "node": {"shape": "square" } }
metadata.tags contains "topic1" : {"node": {"color": "red"} }
```

the rule engine could simply iterate over the rules, and for each match update the values in the config dict (starting from some default). So the above blogpost (with an empty default config) would have to config: `{ "node": {"shape": "square" , "color": "red"} }

Any styling by markdown-links itself, could also be implemented that way, with information that is coming from some other namespace ( not 'metadata' or whatever the name would be).

**Comment by fmagin** [comment]
I have been thinking about this again, and in hindsight it seems overkill for markdown-links to deal with any of the decisions on how to style the nodes by implementing its own rule parsing.
I think the simpler option is to just add support for reading the YAML metadata and retrieving some basic options from there, e.g.:

```yaml
markdown-links-style:
    color: "red" // or any HTML style color specification. Especially because VS Code supports changing them easily incl color preview
    size: 23 // some number to describe the size of the node. Maybe a float as a scaling factor from the default
    shape: "square" // depends on what kind of shapes can be supported, this might be harder and can be a later feature
```

Then users can either easily specify this manually and extension can opt to automatically add it to files depending on whatever they desire. I think that for the most part this will already be quite useful if you can just specify it manually.
